### ISSUE TITLE
[question] 

### ISSUE THREAD

**Issue by Fred-Vatin** [ronilaukkarinen/vscode-stylefmt#2]
### Environment

  * VSCode Version: 1.89.1
  * OS Version: Windows 10 22H2

### Question 1

Hello,

You know those properties like `text-shadow`, `box-shadow`, that can have multiple effects separated by commas. Do you know if there would be a format settings to format:
```css
a {
	box-shadow: 0 0 0 1px rgba(30, 140, 190, 0.8), 0 0 2px 1px rgba(30, 140, 190, 0.8);
}
```

into this:
```css
a {
  box-shadow:
    0 0 0 1px rgba(30, 140, 190, 0.8),
    0 0 2px 1px rgba(30, 140, 190, 0.8);
}
```

And set this in VS Code for all CSS files (not only ones in a project).

### Question 2

A way to sort properties while formatting ?

I suggest opening the **discussion** section in the project to avoid polluting issues section with questions like this.

Best regards.
